### ISSUE TITLE
Regarding Dataset and pretrained checkpoints

### ISSUE THREAD

**Issue by ac5113** [huochf/WildHOI#1]
Hello,
The link to the data in the WildHOI website does not work. Also, the link to the pretrained checkpoints is restricted. Could you please provide these?

**Comment by huochf** [comment]
The WildHOI dataset has not been released. 
We only released the pre-trained checkpoints. Please check if the links in README work now.

**Comment by ac5113** [comment]
Thank you for the information. Could you please tell me when it's planned to be released?
The links work now!
Also, about the pre-trained checkpoint, is it trained solely on the WildHOI dataset?

**Comment by huochf** [comment]
I'm not sure when the data will be released. Once the dataset is released, I will inform you in this issue.
Yes, the pre-trained checkpoints are only trained using the 2.5D KPS in the WildHOI dataset object-by-object.
If you have any additional questions in the meantime, feel free to ask!

**Comment by ac5113** [comment]
Alright, thanks for the info!

**Comment by huochf** [comment]
The dataset is released.
